### ISSUE TITLE
KeyError: 'MEDIA_DIR'

### ISSUE THREAD

**Issue by ivan-ef** [blanky0230/python-udp-vlc#1]
Traceback (most recent call last):
  File "/home/macmac/Downloads/python-ArtNet-vlc-main/src/player/server.py", line 2, in <module>
    from player import VlcPlayer
  File "/home/macmac/Downloads/python-ArtNet-vlc-main/src/player/player.py", line 11, in <module>
    MEDIA_DIR = os.environ['MEDIA_DIR']
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MEDIA_DIR'

looks like 
**load_dotenv()** 
is missing after:
**from dotenv import load_dotenv**

**Comment by blanky0230** [comment]
https://github.com/blanky0230/python-ArtNet-vlc/pull/3
